package com.example.adhd_analyzer;

import com.example.adhd_analyzer.entities.Answer;

public class QuestionAnswer {
    public static String [] question = {
            "1) likes to engage in active activities, sports, etc.",
            "2) Loses objects that are necessary for actions and tasks (lists, pencils, books or tools)",
            "3) Not planning ahead",
            "4) blurts things out unintentionally",
            "5) risk taker or daring",
            "6) Tends to \"go down\" on himself",
            "7) Starts a task but does not finish it",
            "8) Has a low frustration threshold",
            "9) talking too much",
            "10) is in constant motion, \"as if the battery never runs out\"",
            "11) \"messy\" in his surroundings",
            "12) Says what he thinks, lacks tact",
            "13) Difficulty staying still for an extended period of time",
            "14) Difficulty engaging in leisure activities quietly",
            "15) lacks self-confidence",
            "16) Having trouble keeping track of several things at once",
            "17) I'm frantic and in constant motion even when I need to stay put",
            "18) forgetful",
            "19) Easily angered, hot-tempered",
            "20) gets bored easily",
            "21) Leaves his seat even when required to sit",
            "22) Difficulty queuing or waiting your turn",
            "23) There are outbursts of anger",
            "24) Difficulty maintaining attention during a task or work",
            "25) Lover of exciting activities with strong stimulation",
            "26) Avoids challenges due to a feeling of incompetence",
            "27) He felt restless even when he did not move",
            "28) easily distracted from external stimuli",
            "29) Forgetfulness in daily activities",
            "30) Gets angry or upset easily",
            "31) Not a fan of quiet activities such as thinking a lot, planning, monotonous activity",
            "32) Loses things he needs",
            "33) Difficulty being attentive to others",
            "34) tends to give achievements",
            "35) Bursts out or interrupts others",
            "36) Changes plans or works during them",
            "37) On the outside he acts fine but on the inside he feels insecure",
            "38) Always alert and ready to move",
            "39) Makes comments that he later regrets",
            "40) Does not complete assignments unless there is a \"deadline\" for them, a procrastinator",
            "41) Fidgeting nervously or squirming in the chair",
            "42) Makes careless mistakes or has trouble paying attention to details",
            "43) Behaving insensitively towards others without intention",
            "44) Having trouble starting tasks",
            "45) Interferes with others in their activities",
            "46) Sitting still requires a lot of effort",
            "47) prone to mood swings",
            "48) Shows reluctance or has difficulty with tasks that require a lot of thought",
            "49) Distracted when performing daily tasks",
            "50) Restlessness, activity",
            "51) Dependent on others to maintain order and attention to detail",
            "52) Unintentionally disturbs others",
            "53) His attention fluctuates between intense focus and easy distraction.",
            "54) Tendency to frenzy or to fidget nervously",
            "55) Pay attention only to things that interest him",
            "56) Not always sure of his abilities to succeed in different fields",
            "57) Unable to sit for a long time",
            "58) Answered before the question was asked in its entirety",
            "59) Prefers to be on the move than to stay in one place",
            "60) Difficulty completing assignments or work",
            "61) hot tempered",
            "62) Disrupts others in their work or play",
            "63) Past failures lower confidence",
            "64) He is easily distracted by external stimuli",
            "65) Difficulty with order and organization",
            "66) Has an incorrect estimation of times",
    };
    public static String [] answers = new String[66];

    public static QuestionAnswer [] arrayAQ = new QuestionAnswer[66];

}
